---

# general setup

- name: check last time apt was updated
  stat: path=/var/cache/apt/pkgcache.bin
  register: apt_update_details

- name: update apt caches
  become: yes
  # Is the time apt was last updated < the current time - 24 hours?
  when: "apt_update_details.stat.mtime < ansible_date_time.epoch|int  - (60 * 60 * 24)"
  apt: update_cache=yes

- name: Upgrade APT to the latest safe packages
  apt: upgrade=safe

- name: Install required packages
  apt: state=installed name={{ item }}
  with_items: ubuntu_common_required_packages

- name: Install optional packages
  apt: state=installed name={{ item }}
  with_items: ubuntu_common_optional_packages

# TODO: set hostname but don't use it for building clojars
# - name: set hostname
#   hostname: name={{ hostname }}

- name: Set timezone to UTC
  when: ansible_date_time.tz != 'UTC'
  command: timedatectl set-timezone UTC

# TODO: set MOTD with instructions?

# user accounts

- name: ensure admin user accounts exist
  user: name="{{ item.name }}" state=present shell="/bin/bash"
  when: "{{ item.active }}"
  with_items: admins

# To remove accounts, set the admin's 'active' key in private/vars.yml to no,
# then rerun the playbook before removing them from the vars file
- name: remove unneeded admin accounts
  user: name="{{ item.name }}" state=absent remove=yes
  when: "{{ not item.active }}"
  with_items: admins

# includes

- include: rsync.yml
  notify: restart rsync

- include: postfix.yml
  notify: reload postfix

- include: hardening.yml
  become: yes
